// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rhtyx/bayarind-service.git/model (interfaces: SessionRepository)
//
// Generated by this command:
//
//	mockgen -destination=model/mock/mock_session_repository.go -package=mock github.com/rhtyx/bayarind-service.git/model SessionRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/rhtyx/bayarind-service.git/model"
	gomock "go.uber.org/mock/gomock"
)

// MockSessionRepository is a mock of SessionRepository interface.
type MockSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepositoryMockRecorder
}

// MockSessionRepositoryMockRecorder is the mock recorder for MockSessionRepository.
type MockSessionRepositoryMockRecorder struct {
	mock *MockSessionRepository
}

// NewMockSessionRepository creates a new mock instance.
func NewMockSessionRepository(ctrl *gomock.Controller) *MockSessionRepository {
	mock := &MockSessionRepository{ctrl: ctrl}
	mock.recorder = &MockSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepository) EXPECT() *MockSessionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSessionRepository) Create(arg0 context.Context, arg1 *model.Session) (*model.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*model.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSessionRepositoryMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSessionRepository)(nil).Create), arg0, arg1)
}

// DeleteByRefreshToken mocks base method.
func (m *MockSessionRepository) DeleteByRefreshToken(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByRefreshToken", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByRefreshToken indicates an expected call of DeleteByRefreshToken.
func (mr *MockSessionRepositoryMockRecorder) DeleteByRefreshToken(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByRefreshToken", reflect.TypeOf((*MockSessionRepository)(nil).DeleteByRefreshToken), arg0, arg1)
}

// FindByRefreshToken mocks base method.
func (m *MockSessionRepository) FindByRefreshToken(arg0 context.Context, arg1 string) (*model.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByRefreshToken", arg0, arg1)
	ret0, _ := ret[0].(*model.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByRefreshToken indicates an expected call of FindByRefreshToken.
func (mr *MockSessionRepositoryMockRecorder) FindByRefreshToken(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByRefreshToken", reflect.TypeOf((*MockSessionRepository)(nil).FindByRefreshToken), arg0, arg1)
}
